builders:
  modules_builder:
    import: "package:beeper/generators/modules.dart"
    builder_factories: [ "modulesBuilder" ]
    build_extensions: { "$lib$": [ "gen/modules.g.dart" ] }
    build_to: source
    auto_apply: dependents

  commands_builder:
    import: "package:beeper/generators/commands.dart"
    builder_factories: [ "commandsBuilder" ]
    build_extensions: { "$lib$": [ "gen/commands.g.dart" ] }
    build_to: source
    auto_apply: dependents

targets:
  $default:
    builders:
      beeper|modules_builder:
        enabled: true
      beeper|commands_builder:
        enabled: true