name: beeper
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  clock: ^1.0.1
  http: ^0.12.2
  path: ^1.7.0
  postgres: ^2.2.0
  rxdart: ^0.24.1
  shelf_static: ^0.2.8
  stack_trace: ^1.9.6
  strings: ^0.1.2
  tuple: ^1.0.3
  yaml: ^2.2.1

dev_dependencies:
  build_runner: ^1.10.3
  dart_style: ^1.3.8
  fake_async: ^1.1.0
  hotreloader: ^2.0.2
  pedantic: ^1.9.0
  source_gen: ^0.9.7
  test: ^1.14.4
