name: beeper
description: A discord bot.
publish_to: none
version: 0.0.1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  async: ^2.4.2
  beeper_common:
    path: common
  clock: ^1.0.1
  http: ^0.12.2
  path: ^1.7.0
  pointycastle: ^2.0.0
  postgres: ^2.2.0
  rxdart: ^0.26.0
  shelf_proxy: any
  stack_trace: ^1.9.6
  strings: ^0.1.2
  tuple: ^1.0.3
  yaml: ^3.1.0

dev_dependencies:
  build_runner: ^1.10.3
  dart_style: ^1.3.8
  fake_async: ^1.1.0
  hotreloader: ^2.0.2
  pedantic: ^1.9.0
  source_gen: ^0.9.7
  test: ^1.14.4
