name: beeper
description: A sample command-line application.
version: 0.0.1

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  http: ^0.12.2
  clock: ^1.0.1
  path: ^1.7.0
  yaml: ^2.2.1
  tuple: ^1.0.3
  strings: ^0.1.2
  rxdart: ^0.24.1
  postgres: ^2.2.0
  shelf_static: ^0.2.8

dev_dependencies:
  source_gen: ^0.9.7
  build_runner: ^1.10.3
  dart_style: ^1.3.8
  hotreloader: ^2.0.2
  fake_async: ^1.1.0
  pedantic: ^1.9.0
  test: ^1.14.4
